SELECT UPPER('aBcd');
SELECT LOWER('ABcD');

SELECT LTRIM('  ABCD');
SELECT RTRIM('ABCD  ');
SELECT TRIM(' ABCD  ');

SELECT LEFT('ABCD', 2);
SELECT RIGHT('ABCD', 3);

SELECT SUBSTRING('ABCDEF', 2, 2);
SELECT SUBSTRING('ABCDEF', 2);

SELECT LOCATE('c', 'ABCDEF');
SELECT REPLACE('ABCDEF', 'CD', 'Z');
