SELECT NOW(), CURDATE(), CURTIME();

SELECT YEAR(NOW());
SELECT MONTH(NOW());
SELECT HOUR(NOW());
SELECT SECOND(NOW());

SELECT DAYNAME(NOW());
SELECT MONTHNAME(NOW());

SELECT EXTRACT(DAY FROM NOW());